development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL", nil) %>
  channel_prefix: bookshop_staging
  allowed_request_origins:
    - http://localhost:5173

staging:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL", nil) %>
  channel_prefix: bookshop_staging
  allowed_request_origins:
    - https://hub.douglusnguyen.site

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") %>
  channel_prefix: bookshop_production
