development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL", nil) %>
  channel_prefix: bookshop_staging

staging:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL", nil) %>
  channel_prefix: bookshop_staging

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") %>
  channel_prefix: bookshop_production
