default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: nguyenlong
  password: <%= ENV['APPNAME_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: bookshop_development

test:
  <<: *default
  database: bookshop_test

staging:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: bookshop
  username: staging
  host: localhost
  port: 5432
  password: 123456

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: bookshop_development
  username: dev
  host: localhost
  port: 5432
  password: <%= ENV["BOOKSHOP_DATABASE_PASSWORD"] %>
